### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by AlifJamain** [nezamy/just#1]
I got this error message
Fatal error: Uncaught Error: Class "System\App" not found in C:\xampp\htdocs\myRoute\start.php:2 Stack trace: #0 C:\xampp\htdocs\myRoute\public\index.php(12): require() #1 {main} thrown in C:\xampp\htdocs\myRoute\start.php on line 2

**Comment by Nevercold** [comment]
https://github.com/nezamy/just#get-started

**Comment by AlifJamain** [comment]
problem solve...forgot to do php -S localhost:8000

**Comment by NoChizPlz** [comment]
i got same error 
" php -S localhost:8000" does not work

**Comment by Nevercold** [comment]
Composer installed?

**Comment by NoChizPlz** [comment]
> Composer installed?

yes

**Comment by NoChizPlz** [comment]
do i need to run some commands other than php -S  localhost:8000?

**Comment by Nevercold** [comment]
actually not, what comes as error?

**Comment by NoChizPlz** [comment]
Stack trace:
#0 C:\Users\ohua2\PhpstormProjects\DropZone\public\index.php(12): require()
#1 {main}
  thrown in C:\Users\ohua2\PhpstormProjects\DropZone\start.php on line 2
[Tue Mar  1 22:00:42 2022] [::1]:4888 Closing

**Comment by NoChizPlz** [comment]
Fatal error: Uncaught Error: Class 'System\App' not found in C:\Users\ohua2\PhpstormProjects\DropZone\start.php:2 Stack trace: #0 C:\Users\ohua2\PhpstormProjects\DropZone\public\index.php(12): require() #1 {main} thrown in C:\Users\ohua2\PhpstormProjects\DropZone\start.php on line 2

**Comment by Nevercold** [comment]
vendor/autoload.php is loaded? (include/require)

**Comment by NoChizPlz** [comment]
> vendor/autoload.php is loaded? (include/require)

where to put this?

**Comment by Nevercold** [comment]
In the index.php header, under the <?php and use ..;

include __DIR__."/vendor/autoload.php";

**Comment by NoChizPlz** [comment]
yes it is included https://imgur.com/a/W36y9k0

**Comment by Nevercold** [comment]
then I'm afraid I don't know what to do, sorry.

**Comment by NoChizPlz** [comment]
do i need to install composer require nezamy/route ? before using the go ?

**Comment by Nevercold** [comment]
Could be, at /route I think it is also called System/App, and there it works.
